#!/bin/bash

APP='Never Lost'
PRIORITY=3
MSG=''
ETHIP=$(/sbin/ifconfig en0 | grep 'inet ' | awk '{print $2}')
WIFIP=$(/sbin/ifconfig en1 | grep 'inet ' | awk '{print $2}')
if [ -n "$ETHIP"  ]; then
	MSG="ETH: $ETHIP \n"
fi
if [ -n "$WIFIP"  ]; then
	MSG="$MSG""WIFI: $WIFIP"
fi
if [ -z "$MSG"  ]; then
	MSG='No ip found on interfaces'
fi
if [ $1 = "pb" ]
then
	if [ -z $2 ]
	then
		`echo -e "$MSG" | pbcopy`
	else
		echo $2
		if [ $2 = "eth" ]
		then
			`echo "$ETHIP" | pbcopy`
		elif [ $2 = "wifi" ]
		then
			`echo "$WIFIP" | pbcopy`
		fi
	fi
else
	`/usr/local/bin/growlnotify -s -p $PRIORITY -t "$APP" -m "$(echo -e $MSG)"`
fi